### ISSUE TITLE
Figure Out How To Run Morganey From Typescript

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/morganey-vscode-extension#1]
Possible Solutions
- [https://stackoverflow.com/questions/29242529/node-js-run-a-java-program](https://stackoverflow.com/questions/29242529/node-js-run-a-java-program)
- [https://github.com/joeferner/node-java](https://github.com/joeferner/node-java)

**Comment by ForNeVeR** [comment]
@06needhamt I wouldn't recommend you to include `node-java` here. It has many known issues with installation on some operating systems (not only Windows; I believe we had problems on Linux as well). I'd stick to node.js API (i.e. `child_process`).

**Comment by ForNeVeR** [comment]
Also, if you need any TypeScript advice — feel free to ask me! I have rich experience with it and with its integration scenarios into existing and new code bases.

**Comment by 06needhamt** [comment]
I need something that i can directly call a java API with as well as child process to run Morganey itself, what would you recommend for the calling of Java API

**Comment by ForNeVeR** [comment]
Well, actually you have multiple options.
1. You could write an integration server in Java and expose external HTTP, or socket, or pipe API. node.js could ask server to do things using its standard HTTP or TCP functionality. I think that's how the most popular language services are written today. **We'll be able to reuse this server in other editor plugins!**
2. You could make Java program execute your JavaScript code! There's a decent [Nashorn](http://openjdk.java.net/projects/nashorn/) JavaScript engine built in our JDK right now. Although I'm not sure how we would interprocess with it — probably using the same pipes, sockets or HTTP?

Option 1 is probably easier to implement if you're on the Java side; option 2 is probably easier if you're on JavaScript side.

If you will provide some examples of what particular API calls you want to make, I'll probably be able to provide further advice.

**Comment by ForNeVeR** [comment]
cc @rexim @Minoru @Newlifer

**Comment by 06needhamt** [comment]
@ForNeVeR The main APIs i will be accessing are the parser and lambda term APIs like in [the IntelliJ Plugin](https://github.com/morganey-lang/morganey-intellij-plugin/blob/master/scala/src/main/scala/me/rexim/morganey/plugin/scala/ParseTerm.scala)

**Comment by ForNeVeR** [comment]
@06needhamt actually I have a funny idea, let's call it option № 3:

**Instead of calling Java from JavaScript, call Scala.js from JavaScript!**

We could (and I really think it's possible) compile (or try at least) Morganey core with Scala.js compiler. After that it'll be accessible from any JavaScript engine without need to do any interprocess communication.

**Comment by 06needhamt** [comment]
@ForNeVeR This sounds like the best option to me. Do we need to change anything in Morganey or is it just a task in `build.sbt`

**Comment by ForNeVeR** [comment]
We already have a task at Morganey: https://github.com/morganey-lang/Morganey/issues/182 (@rexim, probably we'll need to extract the whole Scala.js story to the new issue?)

I think that'll require some changes in Morganey code or maybe a project structure (to isolate things we won't expose in Scala.js part). And it indeed will require us to change `build.sbt` a bit.

I gonna take some sleep right now, so let's discuss with other guys if anyone's free.

**Comment by rexim** [comment]
https://github.com/morganey-lang/Morganey/issues/182 should be already closed because it was extracted into a separate project https://github.com/morganey-lang/let-morganey-rest. I'm gonna sort out everything on this week Saturday.

I don't like the third option. I'd prefer to stick with the first one, because it's a pretty common and reliable approach which is used by many modern laguages these days.

**Comment by ForNeVeR** [comment]
Alright, in that case I agree with @rexim. Let's stick to Java application option.

@06needhamt, I think you'll be able to either redistribute the JAR file (with the language service) with the vscode plugin, or download it from the plugin release page or from Maven repository on demand.

Your vscode plugin would then start the Java process and talk to it through pipes.

**Comment by 06needhamt** [comment]
@ForNeVeR @rexim Ok then we will go for option 1 should this be in its own repository `morganey-integration-server` perhaps?

**Comment by rexim** [comment]
The first option was also request by @Newlifer for his vim extension. I'm gonna create a story for it.
